rvm: 2.2

sudo: required
services: docker

env:
  matrix:
  - INSTANCE=binary-centos      
  - INSTANCE=binary-ubuntu
  - INSTANCE=binary-debian
  - INSTANCE=source-ubuntu 

#before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.10.0
install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant'

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script: travis_retry chef exec bundle exec rake integration:docker[${INSTANCE}]
notifications:
  email: false
