name             'bosun'
maintainer       'ptQa'
maintainer_email 'ptqa.mail@gmail.com'
license          'Apache 2.0'
description      'Installs and configures bosun-server'
version          '1.0.0'

supports 'ubuntu'
supports 'debian'
supports 'centos'

depends 'poise-service-runit'
depends 'golang'
depends 'chef-sugar'
depends 'apt'
depends 'yum'
